src/emmc.c
src/utils.c
src/utils.h

Resize the filesystem after writing an ext2/3/4 file to utilize the whole partition.

src: Resize filesystem after writing ext2/3/4 file

---

doc/layout-config.rst
src/emmc.c

Add size alignment for expanding partitions. The alignment can be
configured with for each partition individually with 'align'. The
default alignment is 1KiB.

src: emmc: Add configurable size alignment for expanding partitions

---

doc/layout-config.rst
src/emmc.c

Add support for specifying partition flags. These are provided under the key "flags" as a sequence of strings. All flags provided are then enabled for that partition.

Add support for partition flags

---

doc/usage.rst

Note option "prefix" for specifying a path which is prepended to relative input URIs in the layout configuration file.

doc: usage: Note "prefix" option

---

src/emmc.c
src/mount.c
src/mount.h

Use GError in all functions implemented in mount.c to capture error messages and adjust all uses of the functions accordingly.

src: Use GError for mount.c

---

doc/layout-config.rst
src/emmc.c

Verify the checksum of input files before writing to partitions. This
allows verification of archives and raw partition files. This also fixes
the issue of partitions not being mounted for checksum verification.
Requires #7 to be merged first.

Verify checksum before writing data

---

README.rst

Add installation instructions for partup and the documentation. partup is installed in /usr/bin and the documentation in /usr/share/doc.

Document install

---

src/utils.c

Fix null pointer by setting error when uri is empty.

src: utils: Return error when uri is empty

---

doc/layout-config.rst
src/emmc.c
src/utils.c
src/utils.h

Add section 'clean' to layout configuration which deletes content at the
specified location.
Example for deleting the environment saved by u-boot on i.MX8M*:
clean:
- offset: 3840KiB
size: 64KiB
- offset: 3960KiB
size: 64KiB

Add option to clean space on the device

---

doc/layout-config-reference.rst
src/emmc.c
src/utils.c
src/utils.h

The PARTUUID of partitions can be set for each individual GPT partition.
It is implemented with a new mapping `partuuid:` for partitions.
This creates a dependency on `sfdisk` provided by `util-linux` on ubunto and `util-linux-sfdisk" on yocto.

Support setting PARTUUID

---

doc/layout-config-reference.rst

Document behavior for different file types.

doc: layout-config-reference: Document supported file types

---

src/emmc.c

Check if the configured disklabel is supported by libparted and return an error if not.

src: emmc: Check disklabel validity

---

src/utils.c

Fix infinite loop when writing raw files with an input_offset greater than 0.

src: utils: Fix infinite loop when input_offset is used

---

src/main.c

Remove explicit casting to void pointer of argument callback, as this is done anyway. GCC still complains about non-compliant conversion from function pointer to object pointer type:
ISO C forbids conversion of function pointer to object pointer type
As all unit tests and examples in GLib and GTK use the same syntax, we can safely ignore this warning.

src: main: Remove explicit casting of arg callback

---

README.rst
src/emmc.c
src/utils.c
src/utils.h

Creating the filesystem on the first partition could fail when `mkfs` is called before the partition is available. Fix this by waiting for the partitions to be ready after writing the partition layout.
Also, add the output to stderr to the error message.

Fix error on mkfs for first partition

---

src/glib-compat.h
src/mount.c
src/utils.c

Add a GLib compatibility header. Currently, this makes it possible to use g_spawn_check_wait_status() instead of its deprecated version g_spawn_check_exit_status() even in older, incompatible GLib versions.

src: Add GLib compatibility header

---

src/utils.c

Change num_read and input_remaining to unsigned.

src: utils: Fix compiler warning about comparing different signedness

---

meson.build
src/error.h
src/main.c
src/mount.c
src/mount.h

Use libmount from util-linux for mount operations instead of calling mount and umount in a commandline.

src: mount: Use libmount for mounting

---

README.rst
doc/index.rst
doc/meson.build
doc/package.rst
doc/usage.rst
meson.build
src/pu-command.c
src/pu-command.h
src/pu-emmc.c
src/pu-glib-compat.c
src/pu-glib-compat.h
src/pu-main.c
src/pu-mount.c
src/pu-mount.h
src/pu-package.c
src/pu-package.h
src/pu-utils.c
src/pu-utils.h
tests/command.c
tests/helper.c
tests/helper.h
tests/meson.build
tests/package-root.c
tests/package.c

This introduces "commands" for partup, mainly to add support for its new "package" format `.partup`. Currently working commands allow for creating packages, showing their content and installing them to a device. A package includes both the layout configuration file and all needed input files.
This is **work in progress**, so there is still a lot of cleanup and some missing work to do. Some tasks include:

Support for commands and new package format

---

doc/usage.rst
meson.build
src/pu-config.c
src/pu-emmc.c
src/pu-flash.c
src/pu-log.c
src/pu-log.h
src/pu-main.c
src/pu-mount.c
src/pu-utils.c

Improve control over debug output with two new options:
--quiet: redirect all messages to the journal, except for error messages
--debug-domains: enable debug output only for the specified modules
Open points:
- which messages should be debug or normal messages
- add more debug output in `pu-utils` and `pu-mount`
- disable compiler warnings for redefining `G_LOG_DOMAIN`
Supersedes #23

Improve debug output

---

src/pu-mount.c
src/pu-utils.c
src/pu-utils.h
tests/mount-root.c
tests/utils.c

Use libmount instead of libblkid to detect mounted partitions. This fixes a bug introduced in
dab8dae32ade (src: mount: Use libmount in pu_device_mounted) which prevented the use of partup with devices without a partition table.

src: pu-mount: Fix mount detection on devices without partitions

---

.github/workflows/system-tests.yml
README.rst
tests/config/system-tests/gpt.yaml
tests/config/system-tests/msdos.yaml

Test partup by writing to loop device instead of physical device. This is a blackbox test as it tests partup as a whole.
The only change to partup itself is support for loop devices in `pu_device_get_partition_path()`.

Test partup with loop device in github action

---

src/pu-emmc.c
src/pu-log.c
src/pu-log.h
src/pu-main.c
src/pu-package.c

* Improve the regular messages and debug output being printed in the `PuEmmc` module.
* Use `g_message()` logging for printing package output. This allows for showing more detailed output when enabling debug options.
* Add a custom logging writer that can format output messages with color, if supported. The output format is slightly tuned from the default coming from GLib, to be shorter and easier to read.
* Set the default logging level to display regular "messages", instead of the slightly higher level "info". This allows printing regular output with `g_message()` without enabling debug output.
* Split the logging setup function into initializing the writer function and setting the current debug level.
* Allow passing the full debug domain, instead of always prefixing it with "partup-". …

Improve debug and message output with color and more structure

---

tests/command.c

Avoid using g_assert_cmpstrv() because it is not available in GLib version 2.66.

tests: command: Do not use g_assert_cmpstrv()

---

README.rst

partup switched to a package format, reflect this in the readme.

README: Replace old syntax with new package format

---

src/pu-command.c
src/pu-command.h
src/pu-main.c
tests/command.c

Allow passing a command usage overview by using the special option entry `G_OPTION_REMAINING` and its argument description field.

src: command: Allow passing command usage

---

doc/package.rst
src/pu-package.c
src/pu-package.h

The layout configuration file does not need to be named 'layout.yaml' anymore. Any yaml file provided will be recognized as the layout. Providing none or multiple yaml files is an error. Also, update the doc accordingly.

src: package: Allow any .yaml file as layout

---

doc/data/layout-ab-emmc.yaml
doc/data/layout-simple.yaml
doc/layout-config-reference.rst
src/pu-emmc.c
src/pu-flash.c
src/pu-utils.c
src/pu-utils.h
tests/config/raw-non-overlap.yaml
tests/config/raw-overlap-partition-table.yaml
tests/config/raw-overlap-partition.yaml
tests/config/raw-overlap-raw.yaml
tests/config/system-tests/gpt.yaml
tests/config/system-tests/msdos.yaml
tests/utils.c

Relative paths should not use the `file://` scheme so remove all uses of it.
Also remove the workaround that made using this scheme possible with file names.

remove file:// scheme from relative paths

---

src/pu-package.c

Do not check if the package exists before mounting, as this is done in the package mounting function already.

src: package: Remove double check of package when printing

---

README.rst

Add a notice that partup can be installed from the AUR on Arch Linux systems. While at it, give the previous section a proper heading describing building from source.

README: Add Arch Linux installation option

---

doc/data/layout-ab-emmc.yaml
doc/layout-config-reference.rst
src/pu-emmc.c
src/pu-utils.c
src/pu-utils.h

Restructure the way eMMC boot partitions are specified in the layout configuration, so other MMC controls can be added in the future. Make the input for eMMC boot partitions optional, allowing to disable them without any input.

src: emmc: Restructure MMC controls

---

CHANGELOG.rst

Add internal references to all releases in the changelog. This allows linking to specific versions in the documentation.

CHANGELOG: Add references to releases

---

README.rst

These tools are required for fat and ext[234] filesystem creation.

README: Note runtime dependency on dosfstools and e2fsprogs

---

CHANGELOG.rst
README.rst
doc/data/layout-ab-emmc.yaml
doc/data/layout-simple.yaml
doc/layout-config-reference.rst
meson.build
src/pu-config.c
src/pu-config.h
src/pu-main.c
tests/config.c
tests/config/raw-non-overlap.yaml
tests/config/raw-overlap-partition-table.yaml
tests/config/raw-overlap-partition.yaml
tests/config/raw-overlap-raw.yaml
tests/config/simple.yaml
tests/config/system-tests/gpt.yaml
tests/config/system-tests/msdos.yaml

Add a function checking the API version of the configuration file against the current program version and return whether these are compatible. Development versions are considered never to be compatible with stable versions, as development versions broke the API too often.
Add release notes for version 1.0.0.

Release 1.0.0

---

src/pu-main.c
src/pu-package.c
src/pu-package.h
tests/package-root.c

Print the layout configuration of the package in addition to the package files. When printing the layout configuration, remove any empty lines in the output for better readability.
Rename `pu_package_list_contents()` to `pu_package_show_contents()` as the function now also shows the layout configuration, not just the list of files in the package.

src: package: Print layout configuration

---

CHANGELOG.rst

Add a skeleton for release 1.1.0, so it can be referenced in the documentation.

CHANGELOG: Add skeleton for release 1.1.0

---

CHANGELOG.rst
doc/layout-config-reference.rst
src/pu-emmc.c
src/pu-utils.c
src/pu-utils.h

The eMMC boot ack is required for the TI am6xx SoCs.

Add layout config to specify eMMC boot ack

---

doc/index.rst
doc/layout-config-reference.rst
src/pu-utils.c

Add support for the FAT16 filesystem type. Explicitly mention the FAT size when calling mkfs. Run mkfs.fat instead of mkfs.vfat, as the latter is really just a symbolic link to the former.
Check against an empty label in `pu_make_filesystem()` instead of an empty fstype. The fstype check is done previously anyway, and we want to guard against null labels before appending anything.
Fix typo of filesystem type.

Add support for FAT16 filesystem type

---

doc/layout-config-reference.rst
src/pu-emmc.c
src/pu-utils.c
src/pu-utils.h
tests/helper.c
tests/utils.c

Allow passing extra arguments when making the filesystem on a partition.
Do not pass any extra arguments to `pu_make_filesystem()` relevant for mkfs.
Describe the partition option "mkfs-extra-args" and how to use it.

Allow passing extra args to mkfs

---

doc/layout-config-reference.rst

Explicitly list supported filesystem types and since which release they are available.

doc: layout-config-reference: Explicitly list supported filesystems

---

src/pu-command.c

Show the help text by default, if no command is provided. We do this by appending --help to argv when no other options or commands were found.

src: command: Show help text if no command is provided

---

CHANGELOG.rst
doc/layout-config-reference.rst
meson.build
src/pu-checksum.c
src/pu-checksum.h
src/pu-emmc.c
src/pu-file.c
src/pu-file.h
tests/checksum.c

For raw data only, verify the written output data, in addition to the already existing input verification.
First, a checksum is created of the input file while accounting any input offset. Then the data is written as usual to the device. Finally, the written data is verified at the specified output offset against the previously determined checksum.

src: emmc: Verify checksum of written raw output data

---

src/pu-emmc.c
src/pu-file.c
src/pu-file.h
src/pu-log.c
src/pu-utils.c
src/pu-utils.h
tests/file.c
tests/meson.build
tests/utils.c

Move the file related functions pu_file_copy() and pu_file_get_size() to the pu-file module. While at it, rename pu_get_file_size() to pu_file_get_size() for consistency in naming.
Create a new module "file" for all file-related unit tests and use the new file module from the sources for it.

src: pu-file: Move more file related functions

---

src/pu-package.c

Prefix the GError when creating a package failed, instead of overwriting it.

src: package: Prefix error instead of overwriting

---

.readthedocs.yaml
README.rst
doc/build-install.rst
doc/index.rst
doc/requirements.txt

Update all requirements to their latest version.
Update readthedocs to Ubuntu 24.04 and Python 3.12.
Move the build and installation instructions to the Sphinx documentation for better reference.
Describe how to build and install partup in Windows' Subsystem for Linux (WSL).

doc: Add WSL2 build and installation instructions
